name: clean_arxitekture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  carousel_slider: ^5.1.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get: ^4.7.2
  get_it: ^8.0.3
  go_router: ^16.0.0
  http: ^1.4.0
  my_package_for_height: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
